# DataRoot University DS100 Test #2
На проходження тесту виділяється 87 хвилин.

## Python

### 1.  Реалізуйте функцію, яка повертає індекс кортежу, сума елементів якого є найменшою серед кортежів в списку:
У відповідь вивести результат роботи ф-ції для наступного списку:
```
[(10, 20), (1), (30, 56, 25), (10, 20), (33), (40), (200), (10, 42), (42), (1,2,3), (4,5,6), (10,11,12), (7,8,9)]
```


```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [146]:
'''my_list = [(10, 20), (1), (30, 56, 25), (10, 20), (33), (40), (200), (10, 42), (42), (1,2,3), (4,5,6), (10,11,12), (7,8,9)]
for x in my_list:'''
   


'my_list = [(10, 20), (1), (30, 56, 25), (10, 20), (33), (40), (200), (10, 42), (42), (1,2,3), (4,5,6), (10,11,12), (7,8,9)]\nfor x in my_list:'

### 2.  Реалізуйте функцію str -> dict, таку, що ключем dict є слово, а значенням - його кількість в початковій str:
У відповідь вивести результат роботи ф-ції для наступної строки:
```"Text mining, also referred to as text data mining, roughly equivalent to text analytics, is the process of deriving high-quality information from text."```

```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [147]:
import re
from collections import Counter 
s = "Text mining, also referred to as text data mining, roughly equivalent to text analytics, is the process of deriving high-quality information from text."
s_clear = re.split('[^a-z]',s.lower())
d = Counter(s_clear)
d.pop('')
print (d)

Counter({'text': 4, 'mining': 2, 'to': 2, 'also': 1, 'referred': 1, 'as': 1, 'data': 1, 'roughly': 1, 'equivalent': 1, 'analytics': 1, 'is': 1, 'the': 1, 'process': 1, 'of': 1, 'deriving': 1, 'high': 1, 'quality': 1, 'information': 1, 'from': 1})


### 3. Спортсмен почав тренування, пробігши в перший день N км (N - ціле, N > 0). Кожен наступний день він зменшував дистанцію пробігу на Р відсотків від дистанції пробігу попереднього дня(Р - дійсне, 0 < P < 50) до тих пір, коли дистанція пробігу за день стане меншою, ніж N / R (R - ціле, 0 < R < N, N / R - дійсне), після цього дня спортсмен збільшує дистанцію пробігу на Р відсотків від дистанції пробігу попереднього дня, до тих пір, коли дистанція за день стане більшою, ніж N * R, після цього дня виконується початкове правило, тобто дистанція кожного дня зменшується до N/R, а потім збільшується до за вищеописаним циклічним законом. По заданим Р, N, M, R, визначити, після якого дня сумарний пробіг спортсмена за всі дні буде вперше більшим, ніж M км (М - ціле, M > N). Вивести знайдену кількість днів К (K - ціле) і сумарний пробіг за К днів.

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 10хв
```

### 4. Реалізуйте клас Sphere, який створюється за радіусом. Містить два методи, які повертають відповідно: площу поверхні та об'єм.

```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

### 5.  Реалізуйте декоратор, який логує аргументи функцій та повернене значення кожного виклику. А при помилковому виклику відловлює та пише тип помилки. Необхідно виводити як позиційні(```*args```), так й іменовані аргументи(```**kwargs```):

Приклад застосування вашого декоратору в результаті:
```
>>> @log
... def func(*args):
...   return len(args) + sum(args)
>>> func(4, 4, 4)
You called func(4, 4, 4)
It returned 15
15

>>> func(4, 4, "4")
You called func(4, 4, "4")
It Raised TypeError
```

```
```
```
```
```
```
```
Максимальна оцінка: 4 бали
Рекомендований час: 12хв
```

In [148]:
'''def memoize(f):
    results = {}
    def helper(n):
        if n not in results:
            results[n] = f(n)
        return results[n]
    return helper

@memoize
def func(*args,**kwargs):
 '''

'def memoize(f):\n    results = {}\n    def helper(n):\n        if n not in results:\n            results[n] = f(n)\n        return results[n]\n    return helper\n\n@memoize\ndef func(*args,**kwargs):\n '

## Libraries: numpy, scipy, pandas, matplotlib

### Numpy

### 6. Дана матриця:
\begin{align}
A = \begin{bmatrix}
    17 & 24 & 1 & 8 & 15 \\
    23 & 5 & 7 & 14 & 16 \\
    4 & 6 & 13 & 20 & 22 \\
    10 & 12 & 19 & 21 & 3 \\
    11 & 18 & 25 & 2 & 9 \\
\end{bmatrix}
\end{align}


#### Відніміть середнє арифметичне кожного стовпчику від кожного елементу у відповідному стовпчику:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 5хв
```

In [149]:
import numpy as np
import pandas as pd
A = np.array([17,24,1,8,15,23,5,7,14,16, 4,6,13,20,22,10,12,19,21,3,11,18,25,2,9])
B = A.reshape(5,5)
print(B)


[[17 24  1  8 15]
 [23  5  7 14 16]
 [ 4  6 13 20 22]
 [10 12 19 21  3]
 [11 18 25  2  9]]


### 7. Дано наступні матриці:
\begin{align}
A = \begin{bmatrix}
    1 & 24 & 1 & 8 & 15 \\
    -3 & 5 & 7 & -14 & 16 \\
    4 & 6 & -3 & 20 & 2 \\
    10 & 12 & 19 & 21 & 3 \\
    1 & 1 & 2 & -2 & 0 \\
\end{bmatrix}
\end{align}
\begin{align}
\end{align}
\begin{align}
B = \begin{bmatrix}
    17 & 24 & 1 & 8 & 15 \\
    23 & 5 & 7 & 14 & 16 \\
    4 & 6 & 13 & 20 & 22 \\
    10 & 12 & 19 & 21 & 3 \\
    11 & 18 & 25 & 2 & 9 \\
\end{bmatrix}
\end{align}
Знайти:

#### 7.1. Нормалізуйте: $(A B)^{-1}B$
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 2хв
```

#### 7.2. Змініть матрицю B таким чином, щоб всі елементи k, такі що 3 < k < 16, змінили знак.
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

In [150]:
B = np.array([17,24,1,8,15,23,5,7,14,16,4,6,13,20,22,10,12,19,21,3,11,18,25,2,9])
for i in B:
    if (i > 3) & (i < 16):
        B[i] = -i
B.reshape(5,5)

array([[ 17,  24,   1,   8,  -4],
       [ -5,  -6,  -7,  -8,  -9],
       [  4, -11, -12, -13,  22],
       [-15,  12,  19,  21,   3],
       [ 11,  18,  25,   2,   9]])

### 8. Створіть випадковий вектор розміру 10 і замініть максимальне значення на 0
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 4хв
```

In [151]:
arr = np.random.rand(10)
arr

array([ 0.2918113 ,  0.05853937,  0.83246419,  0.07468407,  0.86768166,
        0.05830298,  0.41334989,  0.39731078,  0.86540667,  0.36375153])

In [152]:
arr[arr.argmax()] = 0 
arr

array([ 0.2918113 ,  0.05853937,  0.83246419,  0.07468407,  0.        ,
        0.05830298,  0.41334989,  0.39731078,  0.86540667,  0.36375153])

### Pandas

### 8. Розглянемо наступний словник ```data``` та список ```labels```:

In [153]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

#### 8.1. Створіть ```DataFrame``` ```df``` з даних словника ```data``` з індексами зі списку ```labels```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [154]:
data = pd.DataFrame(data = data, index = labels)

#### 8.2. Відобразіть базову інформацію про цей ```DataFrame``` та його дані:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [155]:
data_frame.describe()

age     visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

#### 8.3. Поверніть перші 5 рядків ```DataFrame``` ```df```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [156]:
data_frame.head(5)

age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3
c  0.5  snake       no       2
d  NaN    dog      yes       3
e  5.0    dog       no       2

#### 8.4. Виберіть стовпчики ```"animal"``` та ```"age"``` з ```DataFrame``` ```df```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [157]:
data_frame.loc[:,['animal','age']]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

#### 8.5 Виберіть дані з рядків ```[1, 5, 8]``` та стовпчиків ```['animal', 'age']```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [158]:
data_frame.iloc[[1,5,8],:].loc[:,['animal','age']]

animal  age
b    cat  3.0
f    cat  2.0
i    dog  7.0

#### 8.6. Виберіть лише ті рядки, в яких к-сть візитів більша ніж 3:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [159]:
data[data['visits'] > 3]

Empty DataFrame
Columns: [age, animal, priority, visits]
Index: []

#### 8.7. Виберіть рядки, де вік відсутній, тобто ```NaN```:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [169]:
data[data['age'].isnull()]

age animal priority  visits
d  NaN    dog      yes       3
h  NaN    cat      yes       1

#### 8.8. Виберіть рядки з котами, вік яких більше ніж 2:
```
```
```
```
```
```
```
Максимальна оцінка: 1 бал
Рекомендований час: 1хв
```

In [170]:
data[data['age']>2]

age animal priority  visits
a  2.5    cat      yes       1
b  3.0    cat      yes       3
e  5.0    dog       no       2
g  4.5  snake       no       1
i  7.0    dog       no       2
j  3.0    dog       no       1

#### 8.9. Підрахуйте середній вік для кожного з типів тварин:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

TypeError: cannot perform reduce with flexible type

#### 8.10. Відсортуйте ```df``` по-перше за віком в спадаючому порядку, по-друге за к-стю візитів в зростаючому порядку:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

#### 8.11. Стовпець "priority" містить значення "yes" та "no". Замінити цей стовпець стовпчиком булевих значень: "yes" на True, а "no" на False:
```
```
```
```
```
```
```
Максимальна оцінка: 2 бали
Рекомендований час: 2хв
```

## Scipy & Matplotlib

### 9. За допомогою scipy згенерувати та за допомогою matplotlib побудувати функцію розподілу ймовірностей для вибірок, правильно підписавши осі та назвавши графік з обраними відповідними параметрами:

#### 9.1. Для виібрки з нормально розподіленої випадкової величини:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.2. Для вибірки з розподілу Бернулі:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.3. Для вибірки з біноміального розподілу:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```

#### 9.4. Для вибірки з розподілу Пуассона:
```
```
```
```
```
```
```
Максимальна оцінка: 3 бали
Рекомендований час: 5хв
```